/**
 * threads.js — canonical thread library data, shared across all pages.
 * Load before main.js and thread.js. Provides: THREAD_INDEX, DOMAIN_LABELS
 */
var THREAD_INDEX = [
  {h:'thread-african-origins-humanity.html',t:'Africa Is the Birthplace of Every Human Being on Earth',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'300,000 BCE – Present'},
  {h:'thread-san-people.html',t:'The San People: The Oldest Continuous Culture on Earth',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'~100,000 BCE – Present'},
  {h:'thread-green-sahara.html',t:'The Green Sahara: When the Desert Was a Fertile Lake District',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'11,000 – 3,000 BCE'},
  {h:'thread-african-empires.html',t:'Before the Chain: 7 African Empires',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'1070 BCE – 1897 CE'},
  {h:'thread-moors.html',t:'Al-Andalus: The Moorish Civilization',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'711 CE – Present'},
  {h:'thread-songhai.html',t:'The Songhai Empire',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'c. 800 CE – 1591'},
  {h:'thread-predynastic-egypt.html',t:'Pre-Dynastic Egypt: The African Roots of the World\'s First Nation-State',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'5000 – 3100 BCE'},
  {h:'thread-imhotep.html',t:'Imhotep: The World\'s First Doctor — and How Hippocrates Got the Credit',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'c. 2650 BCE'},
  {h:'thread-african-mathematics.html',t:"Africa Invented the World's Mathematics",d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'~20,000 BCE – Present'},
  {h:'thread-pharaohs.html',t:'The Black Pharaohs: Egypt\'s African Kings',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'747 – 656 BCE'},
  {h:'thread-aksum.html',t:'The Kingdom of Aksum: Africa\'s Ancient Superpower',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'100 BCE – 940 CE'},
  {h:'thread-great-zimbabwe.html',t:'Great Zimbabwe: The City Europeans Said Africans Couldn\'t Build',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'1100 – 1450 CE'},
  {h:'thread-swahili-coast.html',t:'The Swahili Coast: Africa\'s Global Trade Network',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'800 – 1500 CE'},
  {h:'thread-arab-slave-trade.html',t:'The Arab Slave Trade: 1,300 Years Before the Ships',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'650 CE – 1900s'},
  {h:'thread-mansa-musa.html',t:'Mansa Musa: The Richest Person Who Ever Lived',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'c. 1280 – 1337'},
  {h:'thread-nubia-kush.html',t:'Nubia & the Kingdom of Kush: The Civilization That Ruled Egypt',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'3500 BCE – 350 CE'},
  {h:'thread-african-spiritual-systems.html',t:'African Spiritual Systems: What Was Destroyed and What Survived',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'Ancient – Present'},
  {h:'thread-precolonial-governance.html',t:'Pre-Colonial African Governance: Democracy Before Europe Invented the Word',d:'history-culture',e:1,el:'African Origins',c:'#b8972a',y:'Ancient – 1884'},
  {h:'thread-ife.html',t:'The Kingdom of Ife: Cradle of the Yoruba and the Bronze Heads That Shook the World',d:'history-culture',e:1,el:'African Origins',c:'#5c3d11',y:'500 – 1500 CE'},
  {h:'thread-kanem-bornu.html',t:'The Kanem–Bornu Empire: Africa\'s Longest-Lived Trading Empire',d:'history-culture',e:1,el:'African Origins',c:'#2c4a1e',y:'700 – 1900 CE'},
  {h:'thread-loango.html',t:'The Kingdom of Loango: Central Africa\'s Atlantic Powerhouse',d:'history-culture',e:1,el:'African Origins',c:'#1a5c3a',y:'1300 – 1900 CE'},
  {h:'thread-mapungubwe.html',t:'The Kingdom of Mapungubwe: Africa\'s First Class-Based State',d:'history-culture',e:1,el:'African Origins',c:'#7d5a2f',y:'900 – 1300 CE'},
  {h:'thread-medieval-nubia.html',t:'The Medieval Nubian Kingdoms: Christian Africa\'s Forgotten Civilization',d:'history-culture',e:1,el:'African Origins',c:'#3d1f6e',y:'350 – 1504 CE'},
  {h:'thread-saba.html',t:'The Kingdom of Saba (Sheba): The Queen, the Incense Road, and the African Empire That Traded with Solomon',d:'history-culture',e:1,el:'African Origins',c:'#6b3d00',y:'1000 BCE – 275 CE'},
  {h:'thread-transatlantic-slave-trade.html',t:'The Transatlantic Slave Trade, 1441–1808',d:'history-culture labor-wealth',e:2,el:'The Rupture',c:'#c0392b',y:'1441 – 1808'},
  {h:'thread-slave-ship-resistance.html',t:'Resistance on the Middle Passage',d:'history-culture',e:2,el:'The Rupture',c:'#c0392b',y:'1441 – 1808'},
  {h:'thread-middle-passage.html',t:'The Middle Passage: What the Crossing Cost',d:'history-culture',e:2,el:'The Rupture',c:'#c0392b',y:'1500 – 1808'},
  {h:'thread-code-noir.html',t:'The Code Noir: France Wrote the Rules of Slavery',d:'history-culture',e:2,el:'The Rupture',c:'#c0392b',y:'1685 – Present'},
  {h:'thread-invention-of-race.html',t:'The Invention of Race: Why Racism Was Created',d:'history-culture',e:2,el:'The Rupture',c:'#c0392b',y:'1676 – Present'},
  {h:'thread-blumenbach.html',t:'The Man Who Invented Race: Blumenbach',d:'history-culture',e:2,el:'The Rupture',c:'#c0392b',y:'1775 – Present'},
  {h:'thread-dahomey.html',t:'The Kingdom of Dahomey: The Agojie, the Slave Trade, and the State That Defied Europe',d:'history-culture',e:2,el:'The Rupture',c:'#c0392b',y:'1600 – 1894'},
  {h:'thread-haiti.html',t:'Haiti: The $21 Billion Punishment for Revolution',d:'history-culture labor-wealth',e:2,el:'The Rupture',c:'#c0392b',y:'1791 – Present'},
  {h:'thread-haitian-revolution.html',t:'The Haitian Revolution: The Only Successful Slave Revolt in History',d:'history-culture',e:2,el:'The Rupture',c:'#c0392b',y:'1791 – Present'},
  {h:'thread-france-neocolonialism.html',t:"France's Colonial Tax: 14 Nations Still Pay for Their Own Colonization",d:'history-culture labor-wealth',e:2,el:'The Rupture',c:'#c0392b',y:'1885 – Present'},
  {h:'thread-stolen-labor.html',t:'Stolen Labor: The Architecture of the Racial Wealth Gap',d:'labor-wealth',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1619 – Present'},
  {h:'thread-before-mayflower.html',t:'Before the Mayflower: Black America Before the Founding',d:'history-culture',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1513 – 1861'},
  {h:'thread-abolitionism.html',t:'The Fire Next Time: Black Abolitionists, 1829–1865',d:'history-culture',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1829 – 1865'},
  {h:'thread-slave-revolts.html',t:'The Fire from Below: Slave Revolts & Uprisings',d:'history-culture',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1739 – 1831'},
  {h:'thread-mexico-freedom.html',t:'South to Freedom: Mexico Offered Liberty',d:'history-culture',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1829 – 1865'},
  {h:'thread-seneca-village.html',t:'Seneca Village: Destroyed to Build Central Park',d:'history-culture housing',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1825 – 1857'},
  {h:'thread-weeksville.html',t:'Weeksville: The Free Black City Built Inside Brooklyn',d:'history-culture',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1838 – Present'},
  {h:'thread-black-church.html',t:'The Bombed Church: The Black Church in America',d:'history-culture',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1773 – Present'},
  {h:'thread-black-press.html',t:'The Black Press: Ida B. Wells & the Counter-Record',d:'history-culture',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1827 – Present'},
  {h:'thread-domestic-slave-trade.html',t:'The Domestic Slave Trade: One Million Sold South',d:'labor-wealth history-culture',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1790 – 1860'},
  {h:'thread-frederick-douglass.html',t:'Frederick Douglass: The Man They Could Not Silence',d:'history-culture',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1818 – 1895'},
  {h:'thread-harriet-tubman.html',t:'Harriet Tubman: She Never Lost a Passenger',d:'history-culture',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'c. 1822 – 1913'},
  {h:'thread-harriet-jacobs.html',t:'Harriet Jacobs: The Story Douglass Could Not Tell',d:'history-culture',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'c. 1813 – 1897'},
  {h:'thread-cotton-economy.html',t:'King Cotton: How Slavery Built American Capitalism',d:'labor-wealth',e:3,el:'Slavery & Resistance',c:'#1a6b3a',y:'1793 – 1865'},
  {h:'thread-freedmens-bureau.html',t:'The Freedmen\'s Bureau: America\'s First Attempt at Reparative Justice',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1865 – 1872'},
  {h:'thread-robert-smalls.html',t:'Robert Smalls: He Stole a Confederate Warship',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1839 – 1915'},
  {h:'thread-freedmens-bank.html',t:'The Freedmen\'s Bank: The First Great Theft of Black Savings',d:'labor-wealth history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1865 – 1874'},
  {h:'thread-kkk.html',t:'The Ku Klux Klan: America\'s Terrorist Organization, 1865–Present',d:'history-culture criminal-justice',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1865 – Present'},
  {h:'thread-buffalo-soldiers.html',t:'Buffalo Soldiers: Fighting for a Country That Wouldn\'t Fight for Them',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1866 – 1944'},
  {h:'thread-ebenezer-creek.html',t:'Ebenezer Creek: The Union Army Left Them to Die',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1864'},
  {h:'thread-end-of-slavery.html',t:'How Slavery Really Ended',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1861 – Present'},
  {h:'thread-thirteenth-amendment.html',t:'The Exception That Swallowed the Rule: The 13th Amendment Loophole',d:'criminal-justice history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1865 – Present'},
  {h:'thread-juneteenth.html',t:'Two and a Half Years Late: Juneteenth',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1865 – Present'},
  {h:'thread-black-codes.html',t:'Black Codes: The Law That Re-Enslaved Black America',d:'criminal-justice history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1865 – Present'},
  {h:'thread-opelousas-massacre.html',t:'The Opelousas Massacre: 200–300 Killed to Deliver a Zero-Vote Election',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1868'},
  {h:'thread-colfax-massacre.html',t:'The Colfax Massacre: The Killing That Rewrote Constitutional Law',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1873'},
  {h:'thread-reconstruction.html',t:'Reconstruction: What Was Built and How It Was Destroyed',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1865 – 1877'},
  {h:'thread-hamburg-massacre.html',t:'The Hamburg Massacre: How Reconstruction Died at Gunpoint',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1876 – 1877'},
  {h:'thread-lynching.html',t:'Spectacle and Terror: Lynching as American Policy',d:'history-culture criminal-justice',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1877 – 2022'},
  {h:'thread-fear-of-black-assembly.html',t:'What They Were Afraid Of: Fear of Black Assembly',d:'history-culture criminal-justice',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1739 – Present'},
  {h:'thread-red-summer.html',t:'Red Summer: 26 Cities, One Summer, 1919',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1919'},
  {h:'thread-emmett-till.html',t:'Emmett Till: The Murder That Started a Movement',d:'history-culture criminal-justice',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1955 – Present'},
  {h:'thread-reconstruction-politicians.html',t:'Black Reconstruction: The 2,000 Politicians They Erased',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1868 – 1901'},
  {h:'thread-convict-leasing.html',t:'Convict Leasing: Slavery by Another Name',d:'labor-wealth',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1865 – 1942'},
  {h:'thread-exodusters.html',t:'The Exodusters: 40,000 Black People Flee to Kansas',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1879 – 1880'},
  {h:'thread-hellfighters.html',t:'The 369th Hellfighters: Black Soldiers in WWI',d:'history-culture',e:4,el:'Emancipation & Betrayal',c:'#7a3e3e',y:'1917 – 1919'},
  {h:'thread-sharecropping.html',t:'Sharecropping: The Slavery That Followed Slavery',d:'labor-wealth history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1865 – 1970'},
  {h:'thread-plessy.html',t:'Plessy v. Ferguson: The Supreme Court Legalizes Apartheid',d:'history-culture criminal-justice',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1896 – Present'},
  {h:'thread-voter-suppression-mechanics.html',t:'Voter Suppression Mechanics: The Toolkit That Never Went Away',d:'history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1877 – Present'},
  {h:'thread-garvey.html',t:'Marcus Garvey and the Politics of Black Nationhood',d:'history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1914 – Present'},
  {h:'thread-harlem-renaissance.html',t:'The Harlem Renaissance: Black Intellectual Power, 1920–1935',d:'history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1920 – 1935'},
  {h:'thread-jazz-blues.html',t:'Jazz, Blues & Cultural Theft: Whose Music Is This?',d:'history-culture labor-wealth',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1890s – Present'},
  {h:'thread-great-migration.html',t:'Six Million People: The Great Migration, 1910–1970',d:'history-culture housing',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1910 – Present'},
  {h:'thread-tulsa.html',t:'Black Wall Street: The Tulsa Massacre of 1921',d:'labor-wealth history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1905 – 2023'},
  {h:'thread-thibodaux-massacre.html',t:'The Thibodaux Massacre: What Happened When Black Workers Went on Strike',d:'history-culture labor-wealth',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1887'},
  {h:'thread-corbin-expulsion.html',t:'The Corbin Expulsion: Driven Out in a Single Night',d:'history-culture housing',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1919'},
  {h:'thread-ocoee-massacre.html',t:'The Ocoee Massacre: Election Day, 1920',d:'history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1920'},
  {h:'thread-slocum-massacre.html',t:'The Slocum Massacre: The Killing They Buried Twice',d:'history-culture housing',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1910'},
  {h:'thread-greenwood-pattern.html',t:'The Greenwood Pattern: They Burned It Every Time',d:'labor-wealth history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1898 – 1923'},
  {h:'thread-negro-leagues.html',t:'The Negro Leagues',d:'history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1867 – Present'},
  {h:'thread-hbcus.html',t:'HBCUs: Founded Under Exclusion, $12B Underfunded Today',d:'education',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1837 – Present'},
  {h:'thread-hbcu.html',t:'HBCUs: Founded Under Exclusion, Underfunded for a Century',d:'education',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1837 – Present'},
  {h:'thread-black-culture.html',t:'Black Culture Is American Culture: The Creation That Was Stolen',d:'history-culture labor-wealth',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1619 – Present'},
  {h:'thread-inventors.html',t:'Built by Black Hands: The Inventors America Erased',d:'history-culture labor-wealth',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1821 – Present'},
  {h:'thread-oscarville.html',t:'Oscarville, Georgia: The Erasure of Forsyth County',d:'history-culture housing',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1912 – Present'},
  {h:'thread-lake-marion.html',t:'Lake Marion: The Economy Built Over Ferguson',d:'housing labor-wealth',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1942 – Present'},
  {h:'thread-ida-b-wells.html',t:'Ida B. Wells: The Woman Who Documented American Terror',d:'history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1862 – 1931'},
  {h:'thread-dubois.html',t:'W.E.B. Du Bois: The Architect of Black Consciousness',d:'history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1868 – 1963'},
  {h:'thread-booker-t-washington.html',t:'Booker T. Washington: The Accommodation and Its Cost',d:'history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1856 – 1915'},
  {h:'thread-scottsboro.html',t:'The Scottsboro Boys: Nine Teenagers and the Trial That Exposed American Justice',d:'history-culture',e:5,el:'Jim Crow Era',c:'#5c4a1e',y:'1931 – 1950'},
  {h:'thread-tuskegee.html',t:'Tuskegee Syphilis Study: The U.S. Government\'s Medical Experiment on Black Men',d:'health criminal-justice',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1932 – 1972'},
  {h:'thread-bruces-beach.html',t:'Bruce\'s Beach: The Black Resort Manhattan Beach Stole — and Returned',d:'housing labor-wealth history-culture',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1912 – 2022'},
  {h:'thread-brown-v-board.html',t:'Brown v. Board of Education: The Ruling That Changed America — and Didn\'t',d:'education history-culture',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1954'},
  {h:'thread-golden-thirteen.html',t:'The Golden Thirteen: First Black Naval Officers',d:'history-culture',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1775 – 1987'},
  {h:'thread-gi-bill.html',t:'The GI Bill That Built the White Middle Class',d:'housing labor-wealth',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1944 – Present'},
  {h:'thread-lily-white.html',t:'The Lily White Movement: Party of Lincoln',d:'history-culture',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1877 – 1968'},
  {h:'thread-displacement.html',t:'The Flooded City: Five Ways Black Communities Were Taken',d:'housing labor-wealth',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1898 – Present'},
  {h:'thread-urban-renewal.html',t:'Urban Renewal: The Highway That Ran Through Black America',d:'housing history-culture',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1949 – Present'},
  {h:'thread-double-v.html',t:'The Double V Campaign: Fight Fascism Abroad, Fight Racism at Home',d:'history-culture',e:6,el:'WWII & Post-War',c:'#8b1a1a',y:'1942 – 1945'},
      {h:'thread-eo8802.html',t:'Executive Order 8802: How A. Philip Randolph Forced FDR's Hand',d:'history-culture',e:6,el:'WWII & Post-War',c:'#1a3a6b',y:'1941'},
      {h:'thread-detroit-1943.html',t:'The Detroit Race Riot of 1943: When the War Came Home',d:'history-culture',e:6,el:'WWII & Post-War',c:'#7a2a00',y:'1943'},
      {h:'thread-core.html',t:'CORE and the First Sit-Ins: How Civil Disobedience Was Invented Before Anyone Had a Name for It',d:'history-culture',e:6,el:'WWII & Post-War',c:'#1a4a2a',y:'1942 – 1961'},
{h:'thread-negro-market.html',t:'The Negro Market: When Corporate America Discovered Black Consumers',d:'history-culture labor-wealth',e:6,el:'WWII & Post-War',c:'#5a1a1a',y:'1940 – Present'},
      {h:'thread-tuskegee-airmen.html',t:'The Tuskegee Airmen: 332 Fighters, Zero Bombers Lost',d:'history-culture',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1941 – Present'},
  {h:'thread-redlining.html',t:'Redlining: The Map That Built the Wealth Gap',d:'housing labor-wealth',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1934 – Present'},
  {h:'thread-paul-robeson.html',t:'Paul Robeson: The Man America Tried to Erase',d:'history-culture',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1898 – 1976'},
  {h:'thread-hidden-figures.html',t:'Hidden Figures: The Black Women Who Put America in Space',d:'history-culture',e:6,el:'WWII & Post-War',c:'#1a4a6b',y:'1943 – 1986'},
  {h:'thread-mlk.html',t:'Martin Luther King Jr.: What They Don\'t Teach You',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1929 – 1968'},
  {h:'thread-bayard-rustin.html',t:'Bayard Rustin: The Man They Hid Behind the March',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1912 – 1987'},
  {h:'thread-civil-rights.html',t:'The Movement That Was Not Spontaneous',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1954 – Present'},
  {h:'thread-voting-rights.html',t:'The Right They Keep Taking: Black Voting Rights',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1870 – Present'},
  {h:'thread-self-defense.html',t:'The Right to Defend: Black Organized Self-Defense',d:'history-culture criminal-justice',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1892 – 1982'},
  {h:'thread-black-athletes.html',t:'Shut Up and Play: Ali, Kaepernick, and Athletic Protest',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1908 – Present'},
  {h:'thread-hbcu-football.html',t:'Gridiron Separate and Unequal: HBCU Football',d:'history-culture education',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1892 – Present'},
  {h:'thread-black-panthers.html',t:'What the Panthers Actually Were',d:'history-culture health',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1966 – Present'},
  {h:'thread-statue-of-liberty.html',t:'The Black Statue of Liberty',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1865 – Present'},
  {h:'thread-malcolm-x.html',t:'Malcolm X: By Any Means Necessary',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1925 – 1965'},
  {h:'thread-freedom-riders.html',t:'The Freedom Riders: The Government Knew and Did Nothing',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1961'},
  {h:'thread-birmingham.html',t:'Birmingham: The Four Girls and the Dogs',d:'history-culture criminal-justice',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1963'},
  {h:'thread-black-lgbtq.html',t:'Black LGBTQ+ History: The Revolution Marsha Started',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1969 – Present'},
  {h:'thread-black-mayors.html',t:'Black Political Power: Elected Into a System Built to Constrain Them',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1967 – Present'},
  {h:'thread-fannie-lou-hamer.html',t:'Fannie Lou Hamer: Sick and Tired of Being Sick and Tired',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1917 – 1977'},
  {h:'thread-claudette-colvin.html',t:'Claudette Colvin: She Came Before Rosa Parks',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1939 – Present'},
  {h:'thread-montgomery-bus-boycott.html',t:'The Montgomery Bus Boycott: 381 Days That Changed the Country',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1955 – 1956'},
  {h:'thread-selma.html',t:'Selma and Bloody Sunday: The Bridge That Produced the Voting Rights Act',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1965'},
  {h:'thread-jackson-state.html',t:'Jackson State: The Killing Nobody Remembers',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1970'},
  {h:'thread-16th-street-bombing.html',t:'Four Little Girls: The 16th Street Baptist Church Bombing',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1963'},
  {h:'thread-fred-hampton.html',t:'Fred Hampton: The Chairman They Killed at 21',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1948 – 1969'},
  {h:'thread-shirley-chisholm.html',t:'Shirley Chisholm: Unbought and Unbossed',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1968 – 1983'},
  {h:'thread-black-feminism.html',t:'Black Feminism: The Movement That Was There First',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1851 – Present'},
  {h:'thread-baldwin.html',t:'The Fire Next Time: Baldwin and the White Identity Crisis',d:'history-culture',e:7,el:'Civil Rights',c:'#1a5c3a',y:'1924 – Present'},
  {h:'thread-greensboro-massacre.html',t:'The Greensboro Massacre: They Filmed It and Still Walked Free',d:'history-culture criminal-justice labor-wealth',e:8,el:'Backlash Era',c:'#4a2060',y:'1979'},
  {h:'thread-deindustrialization.html',t:'Deindustrialization: When the Jobs Left Black America',d:'labor-wealth history-culture',e:8,el:'Backlash Era',c:'#4a2060',y:'1970 – Present'},
  {h:'thread-mass-incarceration.html',t:'The 13th: Mass Incarceration & the Second Slavery',d:'criminal-justice',e:8,el:'Backlash Era',c:'#4a2060',y:'1865 – Present'},
  {h:'thread-capital-punishment.html',t:'Capital Punishment: Race, Death, and the American Justice System',d:'criminal-justice',e:8,el:'Backlash Era',c:'#4a2060',y:'1972 – Present'},
  {h:'thread-police.html',t:'Patrol and Punish: The Invention of American Policing',d:'criminal-justice',e:8,el:'Backlash Era',c:'#4a2060',y:'1704 – Present'},
  {h:'thread-media.html',t:'How America Images Blackness',d:'history-culture criminal-justice',e:8,el:'Backlash Era',c:'#4a2060',y:'1915 – Present'},
  {h:'thread-rap-pipeline.html',t:'The Pipeline: How Rap Was Captured',d:'criminal-justice history-culture',e:8,el:'Backlash Era',c:'#4a2060',y:'1973 – Present'},
  {h:'thread-gangs.html',t:'After the Panthers: Origins of the Crips and Bloods',d:'criminal-justice',e:8,el:'Backlash Era',c:'#4a2060',y:'1965 – Present'},
  {h:'thread-white-terror-la.html',t:'Before the Crips: White Terror Gangs in L.A.',d:'history-culture criminal-justice housing',e:8,el:'Backlash Era',c:'#4a2060',y:'1940s – 1969'},
  {h:'thread-subprime.html',t:'The Subprime Trap: 2008 Crisis Built on Black Neighborhoods',d:'housing labor-wealth',e:8,el:'Backlash Era',c:'#4a2060',y:'1990s – Present'},
  {h:'thread-racial-capitalism.html',t:'Same Ledger, New Name: Old Slavery to New Capitalism',d:'labor-wealth',e:8,el:'Backlash Era',c:'#4a2060',y:'1619 – Present'},
  {h:'thread-la-uprising.html',t:'The LA Uprising 1992: Six Days After the Verdict',d:'history-culture criminal-justice',e:8,el:'Backlash Era',c:'#4a2060',y:'1992'},
  {h:'thread-welfare-reform.html',t:'Welfare Reform: Ending Welfare As We Know It',d:'labor-wealth history-culture',e:8,el:'Backlash Era',c:'#4a2060',y:'1996 – Present'},
  {h:'thread-hiv-aids.html',t:'HIV/AIDS and Black America: The Epidemic the Government Ignored',d:'health',e:8,el:'Backlash Era',c:'#4a2060',y:'1981 – Present'},
  {h:'thread-attica.html',t:'Attica: The Massacre the Governor Ordered',d:'history-culture criminal-justice',e:8,el:'Backlash Era',c:'#4a2060',y:'1971'},
  {h:'thread-move-bombing.html',t:'The MOVE Bombing: Philadelphia Dropped a Bomb on Its Own Residents',d:'history-culture criminal-justice',e:8,el:'Backlash Era',c:'#4a2060',y:'1985'},
  {h:'thread-crack-epidemic.html',t:'The Crack Epidemic: The Drug That Was Treated as a Crime',d:'history-culture',e:8,el:'Backlash Era',c:'#4a2060',y:'1984 – 1994'},
  {h:'thread-cointelpro.html',t:"COINTELPRO: The FBI's War on Black America",d:'history-culture criminal-justice',e:8,el:'Backlash Era',c:'#4a2060',y:'1956 – 1971'},
  {h:'thread-banjo-blues.html',t:'The Banjo & the Blues: African Origins of American Music',d:'history-culture music-art',e:3,el:'Slavery & Resistance',c:'#8a5c1a',y:'1600s – Present'},
  {h:'thread-minstrelsy.html',t:'Minstrelsy: How America Learned to See Black People',d:'history-culture music-art',e:3,el:'Slavery & Resistance',c:'#1a1008',y:'1830s – Present'},
  {h:'thread-rb-rock-theft.html',t:"Why R&B Exists: Race Records, Rock & Roll, and the Theft of Black Music",d:'history-culture music-art',e:5,el:'Jim Crow Era',c:'#7a2020',y:'1920s – Present'},
  {h:'thread-michael-jackson.html',t:'Michael Jackson: The Cost of Crossing Over',d:'history-culture music-art labor-wealth',e:8,el:'Backlash Era',c:'#2a1a00',y:'1958 – 2009'},
      {h:'thread-blaxploitation.html',t:'Blaxploitation: Representation, Exploitation, and the Black Hero Hollywood Did Not Expect',d:'history-culture music-art',e:8,el:'Backlash Era',c:'#3a1400',y:'1971 – 1998'},
      {h:'thread-mtv-color-line.html',t:'MTV and the Color Line: How a Cable Channel Tried to Erase Black Music',d:'history-culture music-art media',e:8,el:'Backlash Era',c:'#1a0a3a',y:'1981 – 1988'},
      {h:'thread-prince.html',t:'Prince Rogers Nelson: The Artist, the Masters, and the War for Ownership',d:'history-culture music-art labor-wealth',e:8,el:'Backlash Era',c:'#2d0050',y:'1958 – 2016'},
      {h:'thread-parliament-funkadelic.html',t:'Parliament-Funkadelic: The Mothership, the Groove, and the Architecture of Black Joy',d:'history-culture music-art',e:8,el:'Backlash Era',c:'#0f0a2a',y:'1956 – Present'},
      {h:'thread-nichelle-nichols.html',t:'Nichelle Nichols: Lt. Uhura, MLK, and the Black Woman in Space',d:'history-culture music-art',e:8,el:'Civil Rights Era',c:'#0a1a2a',y:'1932 – 2022'},
      {h:'thread-foia.html',t:'The Freedom of Information Act: Who Owns the Truth About What the Government Did',d:'history-culture criminal-justice',e:8,el:'Accountability Era',c:'#0e2a1a',y:'1966 – Present'},
      {h:'thread-school-to-prison.html',t:'The School-to-Prison Pipeline: How the Education System Feeds the Carceral System',d:'history-culture criminal-justice education',e:8,el:'Carceral Era',c:'#1a0e00',y:'1994 – Present'},
      {h:'thread-medical-apartheid.html',t:'Medical Apartheid: The Dark History of Medical Experimentation on Black Americans',d:'history-culture health',e:8,el:'Colonial Era – Present',c:'#1a0808',y:'1600s – Present'},
      {h:'thread-african-diaspora.html',t:'One Continent: The African Origins of the Entire Human World',d:'history-culture',e:8,el:'Origins & Diaspora',c:'#0a1f0a',y:'300,000 BCE – Present'},
      {h:'thread-we-refuse.html',t:'We Refuse: A Forceful History of Black Resistance',d:'history-culture criminal-justice',e:8,el:'Resistance Era',c:'#1a0505',y:'1619 – Present'},
      {h:'thread-soul-disco.html',t:'Soul, Funk & the Disco Purge',d:'history-culture music-art',e:8,el:'Backlash Era',c:'#5a1a6b',y:'1960s – 1980s'},
  {h:'thread-punk-grunge.html',t:'Punk, Grunge & the Hidden Black Blueprint',d:'history-culture music-art',e:8,el:'Backlash Era',c:'#2a2a2a',y:'1970s – 1990s'},
  {h:'thread-hiphop-origins.html',t:'Hip-Hop: Born from Ruins',d:'history-culture music-art',e:8,el:'Backlash Era',c:'#1a4a1a',y:'1973 – Present'},
  {h:'thread-gangsta-rap.html',t:'Gangsta Rap: Resistance, Exploitation & Self-Destruction',d:'history-culture music-art criminal-justice',e:9,el:'Present Day',c:'#3a1a0a',y:'1988 – Present'},
  {h:'thread-harlem-renaissance.html',t:'The Harlem Renaissance: Black Art Rewrites America',d:'history-culture music-art',e:6,el:'Jim Crow Era',c:'#7a4a00',y:'1910 – 1940'},
  {h:'thread-jacob-lawrence.html',t:'Jacob Lawrence: Migration as Masterpiece',d:'history-culture music-art',e:7,el:'New Deal Era',c:'#1a3a5c',y:'1917 – 2000'},
  {h:'thread-gordon-parks.html',t:'Gordon Parks: Camera as Weapon',d:'history-culture music-art',e:7,el:'New Deal Era',c:'#2a1a00',y:'1912 – 2006'},
  {h:'thread-black-arts-movement.html',t:'The Black Arts Movement: Art as Revolution',d:'history-culture music-art',e:8,el:'Backlash Era',c:'#4a0a0a',y:'1965 – 1975'},
  {h:'thread-black-film.html',t:'Black Film: From Exclusion to Excellence',d:'history-culture music-art',e:5,el:'Jim Crow Era',c:'#0a0a2a',y:'1915 – Present'},
  {h:'thread-graffiti-resistance.html',t:'Graffiti: Writing on the Wall',d:'history-culture music-art',e:9,el:'Present Day',c:'#1a1a3a',y:'1970s – Present'},
  {h:'thread-stamped.html',t:'Stamped: Racist Ideas Were Not Discovered. They Were Invented.',d:'history-culture education',e:9,el:'Present Day',c:'#2a1a5a',y:'1453 – Present'},
      {h:'thread-sky-full-of-elephants.html',t:"A Sky Full of Elephants: What Black Speculative Fiction Sees That History Books Don't",d:'history-culture',e:9,el:'Present Day',c:'#2d1a6b',y:'2024'},
      {h:'thread-what-racism-is.html',t:"What Racism Actually Is: Why "I Don't See Color" Doesn't End It",d:'history-culture',e:9,el:'Present Day',c:'#2a4a6b',y:'1676 – Present'},
  {h:'thread-beverly-tatum.html',t:'Dr. Beverly Tatum: The Smog, the Silence, and Racial Identity',d:'history-culture education',e:9,el:'Present Day',c:'#1a3a2a',y:'1997 – Present'},
  {h:'thread-war-on-black-history.html',t:'The War on Black History: CRT, Book Bans, and the 1619 Project',d:'history-culture education',e:9,el:'Present Day',c:'#2a4a6b',y:'2019 – Present'},
  {h:'thread-algorithmic-racism.html',t:'Algorithmic Racism: How Discrimination Moved into the Machine',d:'history-culture criminal-justice',e:9,el:'Present Day',c:'#2a4a6b',y:'2000 – Present'},
  {h:'thread-katrina.html',t:'Katrina: What the Flood Revealed',d:'housing health',e:9,el:'Present Day',c:'#2a4a6b',y:'2005 – Present'},
  {h:'thread-bail-system.html',t:'The Bail System: Wealth Determines Freedom',d:'criminal-justice',e:9,el:'Present Day',c:'#2a4a6b',y:'Present'},
  {h:'thread-shelby-county.html',t:'Shelby County v. Holder: The Supreme Court Guts the Voting Rights Act',d:'history-culture',e:9,el:'Present Day',c:'#2a4a6b',y:'2013 – Present'},
  {h:'thread-health-disparities.html',t:'The Body as Evidence: Black Health Disparities',d:'health',e:9,el:'Present Day',c:'#2a4a6b',y:'1619 – Present'},
  {h:'thread-healthcare.html',t:'By Design: Why America Has No Universal Healthcare',d:'health',e:9,el:'Present Day',c:'#2a4a6b',y:'1917 – Present'},
  {h:'thread-environmental-racism.html',t:'Environmental Racism: Toxic by Design',d:'health housing',e:9,el:'Present Day',c:'#2a4a6b',y:'1987 – Present'},
  {h:'thread-education.html',t:'Separate Was Never Equal: Black Education in America',d:'education',e:9,el:'Present Day',c:'#2a4a6b',y:'1835 – Present'},
  {h:'thread-black-farmers.html',t:'14 Million Acres: Black Farmers and the USDA',d:'labor-wealth',e:9,el:'Present Day',c:'#2a4a6b',y:'1865 – Present'},
  {h:'thread-ferguson.html',t:'Ferguson, South Carolina: Drowned by the New Deal',d:'housing history-culture',e:9,el:'Present Day',c:'#2a4a6b',y:'1939 – Present'},
  {h:'thread-dei.html',t:'Built to Be Dismantled: The DEI Backlash',d:'labor-wealth history-culture',e:9,el:'Present Day',c:'#2a4a6b',y:'1964 – 2025'},
  {h:'thread-reparations.html',t:'What Is Owed: The Reparations Question',d:'labor-wealth history-culture',e:9,el:'Present Day',c:'#2a4a6b',y:'1865 – Present'},
  {h:'thread-diaspora.html',t:'Before, During, and After: Who Black People Are',d:'history-culture',e:9,el:'Present Day',c:'#2a4a6b',y:'Ancient Africa – Present'},
  {h:'thread-blm.html',t:'Black Lives Matter: The Largest Protest Movement in American History',d:'history-culture',e:9,el:'Present Day',c:'#2a4a6b',y:'2013 – Present'},
  {h:'thread-school-to-prison.html',t:'The School-to-Prison Pipeline: Suspended at Six, Incarcerated at Twenty',d:'criminal-justice education',e:9,el:'Present Day',c:'#2a4a6b',y:'1994 – Present'},
  {h:'thread-affirmative-action.html',t:'Affirmative Action: 45 Years of Policy, Dismantled in One Ruling',d:'education labor-wealth',e:9,el:'Present Day',c:'#2a4a6b',y:'1961 – 2023'},
  {h:'thread-black-maternal-mortality.html',t:'Black Maternal Mortality: Dying to Give Birth in America',d:'health',e:9,el:'Present Day',c:'#2a4a6b',y:'Present'},
  {h:'thread-stand-your-ground.html',t:'Stand Your Ground: The Law That Made Killing Black People Defensible',d:'criminal-justice',e:9,el:'Present Day',c:'#2a4a6b',y:'2005 – Present'},
  {h:'thread-wealth-gap.html',t:'The Racial Wealth Gap: $171,000 vs. $17,150',d:'labor-wealth',e:9,el:'Present Day',c:'#2a4a6b',y:'1865 – Present'},
  {h:'thread-george-floyd.html',t:'George Floyd and the 2020 Uprisings',d:'history-culture',e:9,el:'Present Day',c:'#2a4a6b',y:'2020 – Present'},
  {h:'thread-gentrification.html',t:'Gentrification: The Polite Word for Displacement',d:'housing labor-wealth',e:9,el:'Present Day',c:'#2a4a6b',y:'1970s – Present'},
  {h:'thread-black-mental-health.html',t:'Black Mental Health: The Weight of 400 Years',d:'history-culture',e:9,el:'Present Day',c:'#2a4a6b',y:'Ongoing'}
];

var DOMAIN_LABELS = {
  'history-culture':   'History & Culture',
  'labor-wealth':      'Labor & Wealth',
  'housing':           'Housing',
  'criminal-justice':  'Criminal Justice',
  'education':         'Education',
  'health':            'Health'
};
